package com.hcmut.lms.personalization.application.dto.response.enums;

public enum RecommendationType {
  MAINTAIN_LOAD, FOCUS_HIGH_CREDIT, ADD_ELECTIVES, ACADEMIC_ACTIVITIES, STICK_TO_PLAN, AVOID_LONG_BREAKS, REVIEW_LOAD
  , USE_SUMMER, PRIORITIZE_CORE, REDUCE_LOAD_FOR_GPA, CHOOSE_MANAGEABLE_COURSES, REDUCE_FOR_DEPTH, CONSIDER_DELAY,
  INCREASE_LOAD, ACCEPT_GPA_TRADEOFF, EXTEND_TIMELINE, LOWER_GPA_TARGET, EXTEND_FOR_PREREQUISITES,
  EXTEND_REDUCE_PRESSURE, RECONSIDER_GPA, REDUCE_LOAD_ACCEPT_DELAY, FOCUS_CORE, MAX_LOAD_AND_SUMMER, LOWER_GPA_FOR_TIME
}

