apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: lms_db
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms_db
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_NOTIFICATION_INBOUND_TOPIC: lms.events.notification
  QDRANT_PORT: "6334"
  QDRANT_USE_TLS: "true"
  NOTIFICATION_WS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_ORIGINS: "*"
  FRONT_END: http://localhost:3000
  AWS_REGION: ap-southeast-1
  AWS_PROFILE: lms-wecancode
  SPRING_PROFILES_ACTIVE: prod
  TRANSCRIPTION_CALLBACK_URL: https://dev.viettrandai.xyz/api/coaching-chatbot/v1/transcription-callback
  DOCUMENT_ENRICHMENT_CALLBACK_URL: https://dev.viettrandai.xyz/api/coaching-chatbot/v1/document-enrichment-callback
  MODEL_CACHE_DIR: /tmp/lms-model-cache
