apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  DB_USER: lms_user
  DB_PASSWORD: change-this-db-password
  JWT_SECRET: change-this-long-jwt-secret-min-256-bits
  GEMINI_API_KEY: change-this-gemini-api-key
  QDRANT_API_KEY: lms_qdrant_vector_secret_key
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_FROM: no-reply@your-domain.com
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: lms
type: Opaque
stringData:
  credentials: |
    [lms-wecancode]
    aws_access_key_id = CHANGE_THIS
    aws_secret_access_key = CHANGE_THIS
