package com.hcmut.lms.learning.service.impl;

import com.hcmut.lms.learning.client.CourseManagementClient;
import com.hcmut.lms.learning.client.dto.BatchClassDatasetLookupRequest;
import com.hcmut.lms.learning.client.dto.ClassSectionDatasetResponse;
import com.hcmut.lms.learning.client.dto.SubjectPrerequisiteMapResponse;
import com.hcmut.lms.learning.entity.dataset.GradePredictionDataset;
import com.hcmut.lms.learning.entity.dataset.GradePredictionDatasetVersion;
import com.hcmut.lms.learning.entity.enrollment.Enrollment;
import com.hcmut.lms.learning.exception.ResourceNotFoundException;
import com.hcmut.lms.learning.mapper.GradePredictionDatasetMapper;
import com.hcmut.lms.learning.repository.EnrollmentRepository;
import com.hcmut.lms.learning.repository.GradePredictionDatasetRepository;
import com.hcmut.lms.learning.repository.GradePredictionDatasetVersionRepository;
import com.hcmut.lms.learning.service.GradePredictionDatasetService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class GradePredictionDatasetServiceImpl implements GradePredictionDatasetService {

    private final EnrollmentRepository enrollmentRepository;
    private final GradePredictionDatasetRepository datasetRepository;
    private final GradePredictionDatasetVersionRepository versionRepository;
    private final CourseManagementClient courseManagementClient;
    private final GradePredictionDatasetMapper datasetMapper;

    private static final int BATCH_SIZE = 500;
    /** Shrinkage prior count for course history baseline */
    private static final double SHRINKAGE_K = 10.0;
    /** 3-year window for course history = 30 semKey units */
    private static final int WINDOW_SPAN_COURSE = 30;

    // ─────────────────────────────────────────────────────────────────────────
    // Public entry point
    // ─────────────────────────────────────────────────────────────────────────

    @Override
    @Transactional
    public GradePredictionDatasetVersion computeAndSaveDataset() {
        log.info("Starting grade prediction dataset computation");

        // Create a new version record (status = RUNNING)
        int nextVersionNum = versionRepository.nextVersionNumber();
        GradePredictionDatasetVersion version = GradePredictionDatasetVersion.builder()
                .versionNumber(nextVersionNum)
                .description("Auto-generated by ETL")
                .build();
        version = versionRepository.save(version);
        log.info("Created dataset version #{} (id={})", nextVersionNum, version.getId());

        try {
            int savedCount = doCompute(version);
            version.complete(savedCount);
            version = versionRepository.save(version);
            log.info("Dataset version #{} completed. totalRows={}", nextVersionNum, savedCount);
        } catch (Exception e) {
            log.error("Dataset computation failed for version #{}: {}", nextVersionNum, e.getMessage(), e);
            version.fail();
            versionRepository.save(version);
            throw e;
        }
        return version;
    }

    @Override
    public List<GradePredictionDatasetVersion> getAllVersions() {
        return versionRepository.findAllByOrderByVersionNumberDesc();
    }

    @Override
    public GradePredictionDatasetVersion getVersionById(UUID versionId) {
        return versionRepository.findById(versionId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "GradePredictionDatasetVersion", "id", versionId));
    }

    @Override
    public GradePredictionDatasetVersion getLatestCompletedVersion() {
        return versionRepository.findTopByStatusOrderByVersionNumberDesc(
                        GradePredictionDatasetVersion.DatasetVersionStatus.COMPLETED)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "GradePredictionDatasetVersion", "status", "COMPLETED"));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Core ETL logic (extracted so versioning wrapper can catch exceptions)
    // ─────────────────────────────────────────────────────────────────────────

    private int doCompute(GradePredictionDatasetVersion version) {
        log.info("Running ETL for dataset version #{}", version.getVersionNumber());

        // Phase 1: Load all graded enrollments
        List<Enrollment> gradedEnrollments = enrollmentRepository.findByFinalGradeIsNotNull();
        if (gradedEnrollments.isEmpty()) {
            log.warn("No graded enrollments found. Aborting dataset computation.");
            return 0;
        }
        log.info("Loaded {} graded enrollments", gradedEnrollments.size());

        // Phase 2: Fetch class metadata from course-management-service
        Map<UUID, ClassSectionDatasetResponse> classMetaMap = fetchClassMetadata(gradedEnrollments);

        // Phase 3: Fetch prerequisite mapping (subjectId → set of related subjectIds)
        Map<UUID, Set<UUID>> prereqMap = fetchPrerequisiteMapping();
        log.info("Loaded prerequisite mapping for {} subjects", prereqMap.size());

        // Phase 4: Build enriched enrollment list (skip rows with missing metadata)
        List<EnrichedEnrollment> enriched = buildEnrichedEnrollments(gradedEnrollments, classMetaMap);
        if (enriched.isEmpty()) {
            log.warn("No enrollments could be enriched with class metadata. Aborting.");
            return 0;
        }
        log.info("Enriched {} enrollments successfully", enriched.size());

        // Phase 5: Pre-compute index structures (reduced feature set)
        double globalMedian = computeGlobalMedian(enriched);
        double globalMeanGrade = enriched.stream()
                .mapToDouble(EnrichedEnrollment::courseGrade4pt).average().orElse(0.0);

        Map<UUID, List<EnrichedEnrollment>> byStudent = enriched.stream()
                .collect(Collectors.groupingBy(EnrichedEnrollment::studentId));
        byStudent.values().forEach(list -> list.sort(Comparator.comparingInt(EnrichedEnrollment::semKey)));

        Map<UUID, List<EnrichedEnrollment>> byCourse = enriched.stream()
                .collect(Collectors.groupingBy(EnrichedEnrollment::subjectId));

        Map<String, Integer> semCreditMap = computeSemCreditsMap(enriched);

        // Phase 6: Pre-load existing dataset records for this version to avoid N+1 queries
        Map<String, GradePredictionDataset> existingMap = loadExistingDatasetMapForVersion(version.getId());

        // Phase 7: Per-row computation → raw features (may contain nulls)
        List<RawFeatureRow> rawRows = new ArrayList<>();
        int errorCount = 0;

        for (EnrichedEnrollment row : enriched) {
            try {
                        StudentHistory history = computeStudentHistory(row.studentId(), row.semKey(),
                        byStudent.getOrDefault(row.studentId(), List.of()));

                CourseBaseline baseline = computeCourseBaseline(row.subjectId(), row.semKey(),
                        byCourse.getOrDefault(row.subjectId(), List.of()), globalMedian);

                RelativeCourseResult relative = computeRelativeAvgCourseGrade(
                        row, byStudent, prereqMap);

                int semCredits = semCreditMap.getOrDefault(
                        compositeKey(row.studentId(), row.semesterId()), 0);

                rawRows.add(new RawFeatureRow(row, history, baseline, relative, semCredits));
            } catch (Exception e) {
                log.warn("Feature computation failed for studentId={} subjectId={} semesterId={}: [{}] {}",
                        row.studentId(), row.subjectId(), row.semesterId(),
                        e.getClass().getSimpleName(), e.getMessage());
                errorCount++;
            }
        }

        // Phase 8: Imputation (reduced)
        imputeStudentLevel(rawRows, globalMeanGrade);
        imputeFinalize(rawRows, globalMeanGrade);

        // Phase 9: Build entities and save (with versionId stamped on each row)
        final UUID versionId = version.getId();
        List<GradePredictionDataset> toSave = new ArrayList<>();
        for (RawFeatureRow raw : rawRows) {
            GradePredictionDataset newData = buildEntity(raw, versionId);
            String key = raw.row.studentId() + "|" + raw.row.semesterId() + "|" + raw.row.subjectId();
            GradePredictionDataset entity = existingMap.getOrDefault(key, new GradePredictionDataset());
            datasetMapper.updateFromSource(entity, newData);
            // versionId is ignored by mapper to avoid overwriting; set it explicitly
            entity.setVersionId(versionId);
            toSave.add(entity);
        }

        saveBatch(toSave);
        log.info("doCompute complete for version #{}: success={}, errors={}",
                version.getVersionNumber(), toSave.size(), errorCount);
        return toSave.size();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Data loading
    // ─────────────────────────────────────────────────────────────────────────

    private Map<UUID, ClassSectionDatasetResponse> fetchClassMetadata(List<Enrollment> enrollments) {
        List<UUID> classIds = enrollments.stream()
                .map(Enrollment::getClassId).distinct().toList();

        BatchClassDatasetLookupRequest request = BatchClassDatasetLookupRequest.builder()
                .classIds(classIds).build();

        List<ClassSectionDatasetResponse> responses =
                courseManagementClient.getClassSectionsForDataset(request);

        return responses.stream()
                .filter(r -> r.getClassId() != null)
                .collect(Collectors.toMap(ClassSectionDatasetResponse::getClassId, r -> r, (a, b) -> a));
    }

    /**
     * Fetch prerequisite + recommendation mapping from course-management-service.
     * Returns Map&lt;subjectId, Set&lt;relatedSubjectId&gt;&gt;.
     */
    private Map<UUID, Set<UUID>> fetchPrerequisiteMapping() {
        try {
            List<SubjectPrerequisiteMapResponse> responses =
                    courseManagementClient.getPrerequisiteMapping();
            Map<UUID, Set<UUID>> map = new HashMap<>();
            for (SubjectPrerequisiteMapResponse r : responses) {
                if (r.getSubjectId() != null && r.getRelatedSubjectIds() != null) {
                    map.put(r.getSubjectId(), new HashSet<>(r.getRelatedSubjectIds()));
                }
            }
            return map;
        } catch (Exception e) {
            log.warn("Failed to fetch prerequisite mapping, proceeding without it: {}", e.getMessage());
            return Map.of();
        }
    }

    private List<EnrichedEnrollment> buildEnrichedEnrollments(
            List<Enrollment> enrollments,
            Map<UUID, ClassSectionDatasetResponse> classMetaMap) {

        Map<UUID, ClassSectionDatasetResponse> validMeta = new HashMap<>();
        for (Enrollment e : enrollments) {
            ClassSectionDatasetResponse meta = classMetaMap.get(e.getClassId());
            if (meta != null && meta.getSubjectId() != null && meta.getSemesterId() != null
                    && meta.getSemKey() != null) {
                validMeta.put(e.getClassId(), meta);
            }
        }

        List<Enrollment> sorted = enrollments.stream()
                .filter(e -> validMeta.containsKey(e.getClassId()))
                .sorted(Comparator.comparingInt(e -> validMeta.get(e.getClassId()).getSemKey()))
                .toList();

        Map<String, Integer> attemptCounter = new HashMap<>();
        List<EnrichedEnrollment> result = new ArrayList<>();
        for (Enrollment e : sorted) {
            ClassSectionDatasetResponse meta = validMeta.get(e.getClassId());
            double raw = e.getFinalGrade();
            double grade4 = convertTo4Point(raw);

            String attemptKey = e.getStudentId() + "|" + meta.getSubjectId();
            int attemptIndex = attemptCounter.getOrDefault(attemptKey, 0);
            attemptCounter.put(attemptKey, attemptIndex + 1);

            result.add(new EnrichedEnrollment(
                    e.getStudentId(),
                    e.getClassId(),
                    meta.getSubjectId(),
                    meta.getSemesterId(),
                    meta.getSemKey(),
                    meta.getCredits() != null ? meta.getCredits() : 0,
                    raw,
                    grade4,
                    attemptIndex,
                    meta.getCurriculumSectionId()
            ));
        }
        return result;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Grade conversion (matches Python: A+ & A both → 4.0)
    // ─────────────────────────────────────────────────────────────────────────

    static double convertTo4Point(double grade10) {
        if (grade10 >= 8.5) return 4.0;   // A+ (>=9.5) and A (8.5–9.4) → 4.0
        if (grade10 >= 8.0) return 3.5;   // B+
        if (grade10 >= 7.0) return 3.0;   // B
        if (grade10 >= 6.5) return 2.5;   // C+
        if (grade10 >= 5.5) return 2.0;   // C
        if (grade10 >= 5.0) return 1.5;   // D+
        if (grade10 >= 4.0) return 1.0;   // D
        return 0.0;                        // F
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Pre-compute helpers
    // ─────────────────────────────────────────────────────────────────────────

    private double computeGlobalMedian(List<EnrichedEnrollment> enriched) {
        List<Double> grades = enriched.stream()
                .map(EnrichedEnrollment::courseGrade4pt).sorted().toList();
        if (grades.isEmpty()) return 0.0;
        return median(grades);
    }

    private Map<String, Integer> computeSemCreditsMap(List<EnrichedEnrollment> enriched) {
        Map<String, Integer> map = new HashMap<>();
        for (EnrichedEnrollment e : enriched) {
            String key = compositeKey(e.studentId(), e.semesterId());
            map.merge(key, e.credits(), Integer::sum);
        }
        return map;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Per-row feature computation
    // ─────────────────────────────────────────────────────────────────────────

    private StudentHistory computeStudentHistory(UUID studentId, int currentSemKey,
                                                  List<EnrichedEnrollment> studentRows) {
        List<EnrichedEnrollment> prior = studentRows.stream()
                .filter(r -> r.semKey() < currentSemKey).toList();

        if (prior.isEmpty()) return StudentHistory.empty();

        Set<Integer> priorSemKeys = prior.stream()
                .map(EnrichedEnrollment::semKey).collect(Collectors.toSet());
        int numSemestersPrior = priorSemKeys.size();

        // Cumulative credit-weighted avg (= current_gpa in Python)
        double sumWeightedGrade = 0, sumCredits = 0;
        for (EnrichedEnrollment r : prior) {
            sumWeightedGrade += r.courseGrade4pt() * r.credits();
            sumCredits += r.credits();
        }
        Double cumulativeAvg = sumCredits > 0 ? sumWeightedGrade / sumCredits : null;

        // Previous semester avg (latest semKey)
        int prevSemKey = priorSemKeys.stream().mapToInt(x -> x).max().orElse(0);
        List<EnrichedEnrollment> prevSemRows = prior.stream()
                .filter(r -> r.semKey() == prevSemKey).toList();
        double prevSumWG = 0, prevSumC = 0;
        for (EnrichedEnrollment r : prevSemRows) {
            prevSumWG += r.courseGrade4pt() * r.credits();
            prevSumC += r.credits();
        }
        Double prevSemAvg = prevSumC > 0 ? prevSumWG / prevSumC : null;

        return new StudentHistory(numSemestersPrior, cumulativeAvg, prevSemAvg);
    }

    private CourseBaseline computeCourseBaseline(UUID subjectId, int currentSemKey,
                                                  List<EnrichedEnrollment> courseRows,
                                                  double globalMedian) {
        int windowLow = currentSemKey - WINDOW_SPAN_COURSE;
        List<EnrichedEnrollment> window = courseRows.stream()
                .filter(r -> r.semKey() >= windowLow && r.semKey() < currentSemKey).toList();

        int histCount = window.size();
        boolean histMissing = histCount == 0;

        Double rawMedian = histMissing ? null
                : median(window.stream().map(EnrichedEnrollment::courseGrade4pt).toList());

        double histMedianSmooth = histMissing
                ? 0.0
                : (rawMedian * histCount + globalMedian * SHRINKAGE_K)
                    / (histCount + SHRINKAGE_K);

        return new CourseBaseline(histCount, histMedianSmooth, histMissing);
    }

    /**
     * Compute relative course features using UNION of:
     * <ol>
     *   <li>Same curriculumSectionId (subjects in the same curriculum section)</li>
     *   <li>Prerequisite / Recommended courses (from course_prerequisites table)</li>
     * </ol>
     * Only uses courses the student took in PRIOR semesters (no data leakage).
     * Matches Python: add_relative_course_features()
     */
    private RelativeCourseResult computeRelativeAvgCourseGrade(
            EnrichedEnrollment row,
            Map<UUID, List<EnrichedEnrollment>> byStudent,
            Map<UUID, Set<UUID>> prereqMap) {

        List<EnrichedEnrollment> studentPrior = byStudent.getOrDefault(row.studentId(), List.of())
                .stream()
                .filter(r -> r.semKey() < row.semKey())
                .toList();

        if (studentPrior.isEmpty()) {
            return new RelativeCourseResult(false, null);
        }

        // Build UNION mask: same curriculumSectionId OR is prerequisite/recommended of current course
        Set<UUID> relatedSubjectIds = prereqMap.getOrDefault(row.subjectId(), Set.of());
        UUID currentCurriculumSectionId = row.curriculumSectionId();

        List<EnrichedEnrollment> relatedRows = studentPrior.stream()
                .filter(r -> {
                    // 1) Same curriculum section (subjects in same section are related)
                    if (currentCurriculumSectionId != null
                            && currentCurriculumSectionId.equals(r.curriculumSectionId())) {
                        return true;
                    }
                    // 2) Is prerequisite/recommended of current course
                    return relatedSubjectIds.contains(r.subjectId());
                })
                .toList();

        if (relatedRows.isEmpty()) {
            return new RelativeCourseResult(false, null);
        }

        // Credit-weighted avg grade
        double sumWG = 0, sumC = 0;
        for (EnrichedEnrollment r : relatedRows) {
            sumWG += r.courseGrade4pt() * r.credits();
            sumC += r.credits();
        }
        double relativeAvg = sumC > 0 ? sumWG / sumC : relatedRows.stream()
                .mapToDouble(EnrichedEnrollment::courseGrade4pt).average().orElse(0.0);

        return new RelativeCourseResult(true, relativeAvg);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // IMPUTATION — matching Python pipeline (impute_student_level,
    // add_course_history_baseline, impute_course_level, finalize_other_features)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Step 1: Student-level imputation (reduced).
     * Missing GPA fields default to 0.
     */
    private void imputeStudentLevel(List<RawFeatureRow> rows, double globalMeanGrade) {
        rows.sort(Comparator.comparingInt(r -> r.row.semKey()));

        for (RawFeatureRow raw : rows) {
            boolean needsImpute = raw.history.numSemestersPrior() <= 0
                    || raw.history.cumulativeGradeAvg() == null;

            if (needsImpute) {
                raw.imputedCumulativeGradeAvg = 0.0;
                raw.imputedPreviousSemGradeAvg = 0.0;
            } else {
                raw.imputedCumulativeGradeAvg = orDefault(raw.history.cumulativeGradeAvg(), 0.0);
                raw.imputedPreviousSemGradeAvg = orDefault(raw.history.previousSemGradeAvg(), 0.0);
            }
        }
    }

    /**
     * Step 2: Finalize other features (reduced).
     * relative_avg_course_grade defaults to previous semester GPA or 0 when missing.
     */
    private void imputeFinalize(List<RawFeatureRow> rows, double globalMeanGrade) {
        for (RawFeatureRow raw : rows) {
            if (!raw.relative.hasRelative()) {
                raw.imputedRelativeAvg = raw.imputedPreviousSemGradeAvg != null
                        ? raw.imputedPreviousSemGradeAvg : 0.0;
            } else {
                raw.imputedRelativeAvg = orDefault(raw.relative.relativeAvg(), 0.0);
            }

            raw.imputedCumulativeGradeAvg = orDefault(raw.imputedCumulativeGradeAvg, 0.0);
            raw.imputedPreviousSemGradeAvg = orDefault(raw.imputedPreviousSemGradeAvg, 0.0);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Entity builder and persistence
    // ─────────────────────────────────────────────────────────────────────────

    private GradePredictionDataset buildEntity(RawFeatureRow raw, UUID versionId) {
        EnrichedEnrollment row = raw.row;

        return GradePredictionDataset.builder()
                .studentId(row.studentId())
                .semesterId(row.semesterId())
                .subjectId(row.subjectId())
                .versionId(versionId)
                .courseGrade(row.courseGrade4pt())
                .semCredits(raw.semCredits)
                .semCreditsSquared(raw.semCredits * raw.semCredits)
                .retakeNo(row.attemptIndex())
                .numSemestersPrior(raw.history.numSemestersPrior())
                .cumulativeGradeAvg(raw.imputedCumulativeGradeAvg)
                .previousSemGradeAvg(raw.imputedPreviousSemGradeAvg)
                .subjectHistMedianSmooth(raw.baseline.histMedianSmooth())
                .relativeAvgCourseGrade(raw.imputedRelativeAvg)
                .build();
    }

    private Map<String, GradePredictionDataset> loadExistingDatasetMapForVersion(UUID versionId) {
        // ✅ FIXED: Use repository method with WHERE clause instead of loading all rows
        return datasetRepository.findByVersionId(versionId).stream()
                .collect(Collectors.toMap(
                        d -> d.getStudentId() + "|" + d.getSemesterId() + "|" + d.getSubjectId(),
                        d -> d, (a, b) -> a));
    }

    private void saveBatch(List<GradePredictionDataset> entities) {
        for (int i = 0; i < entities.size(); i += BATCH_SIZE) {
            int end = Math.min(i + BATCH_SIZE, entities.size());
            datasetRepository.saveAll(entities.subList(i, end));
            log.debug("Saved batch {}/{}", end, entities.size());
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Utility methods
    // ─────────────────────────────────────────────────────────────────────────

    private double median(List<Double> values) {
        if (values.isEmpty()) return 0.0;
        List<Double> sorted = values.stream().sorted().toList();
        int mid = sorted.size() / 2;
        return sorted.size() % 2 == 0
                ? (sorted.get(mid - 1) + sorted.get(mid)) / 2.0
                : sorted.get(mid);
    }

    private String compositeKey(UUID a, UUID b) {
        return a + "|" + b;
    }

    private static double orDefault(Double value, double defaultVal) {
        return value != null ? value : defaultVal;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private nested records & classes
    // ─────────────────────────────────────────────────────────────────────────

    private record EnrichedEnrollment(
            UUID studentId,
            UUID classId,
            UUID subjectId,
            UUID semesterId,
            int semKey,
            int credits,
            double finalGrade10pt,
            double courseGrade4pt,
            int attemptIndex,
            UUID curriculumSectionId
    ) {}

    private record StudentHistory(
            int numSemestersPrior,
            Double cumulativeGradeAvg,
            Double previousSemGradeAvg
    ) {
        static StudentHistory empty() {
            return new StudentHistory(0, null, null);
        }
    }

    private record CourseBaseline(
            int histCount,
            double histMedianSmooth,
            boolean histMissing
    ) {
    }

    private record RelativeCourseResult(
            boolean hasRelative,
            Double relativeAvg
    ) {}

    /**
     * Mutable container holding raw features + imputed values for one row.
     * Fields are filled in phases: Phase 7 (raw), then Phase 8 (imputation steps 1-4).
     */
    private static class RawFeatureRow {
        final EnrichedEnrollment row;
        final StudentHistory history;
        final CourseBaseline baseline;
        final RelativeCourseResult relative;
        final int semCredits;

        // Imputed student-level (Step 1)
        Double imputedCumulativeGradeAvg;
        Double imputedPreviousSemGradeAvg;

        // Imputed relative (Step 4)
        double imputedRelativeAvg;

        RawFeatureRow(EnrichedEnrollment row, StudentHistory history, CourseBaseline baseline,
                      RelativeCourseResult relative, int semCredits) {
            this.row = row;
            this.history = history;
            this.baseline = baseline;
            this.relative = relative;
            this.semCredits = semCredits;
        }
    }
}
