package com.hcmut.lms.learning.service.impl;

import com.hcmut.lms.learning.client.CourseManagementClient;
import com.hcmut.lms.learning.client.dto.BatchClassDatasetLookupRequest;
import com.hcmut.lms.learning.client.dto.ClassSectionDatasetResponse;
import com.hcmut.lms.learning.client.dto.SubjectPrerequisiteMapResponse;
import com.hcmut.lms.learning.entity.dataset.GradePredictionDataset;
import com.hcmut.lms.learning.entity.dataset.GradePredictionDatasetVersion;
import com.hcmut.lms.learning.entity.enrollment.Enrollment;
import com.hcmut.lms.learning.entity.subject.SubjectSemesterMetrics;
import com.hcmut.lms.learning.exception.ResourceNotFoundException;
import com.hcmut.lms.learning.mapper.GradePredictionDatasetMapper;
import com.hcmut.lms.learning.repository.EnrollmentRepository;
import com.hcmut.lms.learning.repository.GradePredictionDatasetRepository;
import com.hcmut.lms.learning.repository.GradePredictionDatasetVersionRepository;
import com.hcmut.lms.learning.service.GradePredictionDatasetService;
import com.hcmut.lms.learning.service.SubjectSemesterMetricsService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

import static com.hcmut.lms.learning.util.GradeConversionUtil.convertTo4Point;

@Service
@RequiredArgsConstructor
@Slf4j
public class GradePredictionDatasetServiceImpl implements GradePredictionDatasetService {
  private final EnrollmentRepository enrollmentRepository;
  private final GradePredictionDatasetRepository datasetRepository;
  private final GradePredictionDatasetVersionRepository versionRepository;
  private final CourseManagementClient courseManagementClient;
  private final GradePredictionDatasetMapper datasetMapper;
  private final SubjectSemesterMetricsService subjectSemesterMetricsService;

  private static final int BATCH_SIZE = 500;

  @Override
  @Transactional
  public GradePredictionDatasetVersion computeAndSaveDataset() {
    log.info("Starting grade prediction dataset computation");

    // Check if there's already a RUNNING version to prevent duplicate processing
    Optional<GradePredictionDatasetVersion> runningVersion = versionRepository.findTopByStatusOrderByVersionNumberDesc(
        GradePredictionDatasetVersion.DatasetVersionStatus.RUNNING);
    if (runningVersion.isPresent()) {
      log.warn(
          "Dataset version #{} is already RUNNING. Skipping new computation.",
          runningVersion.get().getVersionNumber());
      return runningVersion.get();
    }

    // Step 1: Compute subject semester metrics first (required for course baseline)
    log.info("Step 1: Computing subject semester metrics...");
    int metricsCount = subjectSemesterMetricsService.computeAndSaveAllMetrics();
    log.info("Subject semester metrics computed: {} records", metricsCount);

    // Create a new version record (status = RUNNING)
    int nextVersionNum = versionRepository.nextVersionNumber();
    GradePredictionDatasetVersion version = GradePredictionDatasetVersion.builder()
        .versionNumber(nextVersionNum)
        .description("Auto-generated by ETL")
        .build();
    version = versionRepository.save(version);
    log.info("Created dataset version #{} (id={})", nextVersionNum, version.getId());

    try {
      int savedCount = doCompute(version);
      version.complete(savedCount);
      version = versionRepository.save(version);
      log.info("Dataset version #{} completed. totalRows={}", nextVersionNum, savedCount);
    } catch (Exception e) {
      log.error("Dataset computation failed for version #{}: {}", nextVersionNum, e.getMessage(), e);
      version.fail();
      versionRepository.save(version);
      throw e;
    }
    return version;
  }

  @Override
  public List<GradePredictionDatasetVersion> getAllVersions() {
    return versionRepository.findAllByOrderByVersionNumberDesc();
  }

  @Override
  public GradePredictionDatasetVersion getVersionById(UUID versionId) {
    return versionRepository.findById(versionId)
        .orElseThrow(() -> new ResourceNotFoundException("GradePredictionDatasetVersion", "id", versionId));
  }

  @Override
  public GradePredictionDatasetVersion getLatestCompletedVersion() {
    return versionRepository.findTopByStatusOrderByVersionNumberDesc(
            GradePredictionDatasetVersion.DatasetVersionStatus.COMPLETED)
        .orElseThrow(() -> new ResourceNotFoundException("GradePredictionDatasetVersion", "status", "COMPLETED"));
  }

  @Transactional
  protected int doCompute(GradePredictionDatasetVersion version) {
    log.info("Running ETL for dataset version #{}", version.getVersionNumber());

    // Phase 1: Load all graded enrollments
    List<Enrollment> gradedEnrollments = enrollmentRepository.findByFinalGradeIsNotNull();
    if (gradedEnrollments.isEmpty()) {
      log.warn("No graded enrollments found. Aborting dataset computation.");
      return 0;
    }
    log.info("Loaded {} graded enrollments", gradedEnrollments.size());

    // Phase 2: Fetch class metadata from course-management-service
    Map<UUID, ClassSectionDatasetResponse> classMetaMap = fetchClassMetadata(gradedEnrollments);

    // Phase 3: Fetch prerequisite mapping (subjectId → set of related subjectIds)
    Map<UUID, Set<UUID>> prereqMap = fetchPrerequisiteMapping();
    log.info("Loaded prerequisite mapping for {} subjects", prereqMap.size());

    // Phase 4: Build enriched enrollment list (skip rows with missing metadata)
    List<EnrichedEnrollment> enriched = buildEnrichedEnrollments(gradedEnrollments, classMetaMap);
    if (enriched.isEmpty()) {
      log.warn("No enrollments could be enriched with class metadata. Aborting.");
      return 0;
    }
    log.info("Enriched {} enrollments successfully", enriched.size());

    Map<UUID, List<EnrichedEnrollment>> byStudent = enriched.stream()
        .collect(Collectors.groupingBy(EnrichedEnrollment::studentId));
    byStudent.values().forEach(list -> list.sort(Comparator.comparingInt(EnrichedEnrollment::semKey)));

    Map<String, Integer> semCreditMap = computeSemCreditsMap(enriched);

    // Phase 5: Batch load all subject semester metrics upfront (avoid N+1)
    Map<String, SubjectSemesterMetrics> metricsMap = batchLoadSubjectSemesterMetrics(enriched);
    log.info("Batch loaded {} subject semester metrics", metricsMap.size());

    // Phase 6: Per-row computation → raw features (may contain nulls)
    List<RawFeatureRow> rawRows = new ArrayList<>();
    int errorCount = 0;

    for (EnrichedEnrollment row : enriched) {
      try {
        StudentHistory history = computeStudentHistory(
            row.semKey(),
            byStudent.getOrDefault(row.studentId(), List.of()));

        CourseBaseline baseline = computeCourseBaseline(row.subjectId(), row.semesterId(), metricsMap);
        log.debug(
            "Computed baseline for subjectId={} semesterId={}: histCount={}, histMedianSmooth={}, histMissing={}",
            row.subjectId(), row.semesterId(), baseline.histCount(), baseline.histMedianSmooth(),
            baseline.histMissing());

        RelativeCourseResult relative = computeRelativeAvgCourseGrade(row, byStudent, prereqMap);
        log.debug(
            "Computed relative course feature for studentId={} subjectId={} semesterId={}: hasRelative={}, " +
                "relativeAvg={}",
            row.studentId(), row.subjectId(), row.semesterId(), relative.hasRelative(), relative.relativeAvg());

        int semCredits = semCreditMap.getOrDefault(compositeKey(row.studentId(), row.semesterId()), 0);

        rawRows.add(new RawFeatureRow(row, history, baseline, relative, semCredits));
      } catch (Exception e) {
        log.warn(
            "Feature computation failed for studentId={} subjectId={} semesterId={}: [{}] {}", row.studentId(),
            row.subjectId(), row.semesterId(), e.getClass().getSimpleName(), e.getMessage());
        errorCount++;
      }
    }

    // Phase 8: Impute missing values, then filter to only complete records
    imputeStudentLevel(rawRows);
    imputeFinalize(rawRows);

    List<RawFeatureRow> completeRows = rawRows.stream().filter(this::hasCompleteData).toList();
    int filteredCount = rawRows.size() - completeRows.size();
    if (filteredCount > 0) {
      log.info("Filtered out {} records with imputed features", filteredCount);
    }

    // Phase 9: Build entities and save using UPSERT (no need to load existing first)
    final UUID versionId = version.getId();
    List<GradePredictionDataset> toSave = new ArrayList<>();
    for (RawFeatureRow raw : completeRows) {
      GradePredictionDataset entity = buildEntity(raw, versionId);
      toSave.add(entity);
    }

    upsertBatch(toSave, version.getId());
    log.info("doCompute complete: saved={}, filtered={}, errors={}", toSave.size(), filteredCount, errorCount);
    return toSave.size();
  }

  private Map<UUID, ClassSectionDatasetResponse> fetchClassMetadata(List<Enrollment> enrollments) {
    List<UUID> classIds = enrollments.stream().map(Enrollment::getClassId).distinct().toList();

    BatchClassDatasetLookupRequest request = BatchClassDatasetLookupRequest.builder().classIds(classIds).build();

    List<ClassSectionDatasetResponse> responses = courseManagementClient.getClassSectionsForDataset(request);

    return responses.stream()
        .filter(r -> r.getClassId() != null)
        .collect(Collectors.toMap(ClassSectionDatasetResponse::getClassId, r -> r, (a, b) -> a));
  }

  /**
   * Fetch prerequisite + recommendation mapping from course-management-service.
   * Returns Map&lt;subjectId, Set&lt;relatedSubjectId&gt;&gt;.
   */
  private Map<UUID, Set<UUID>> fetchPrerequisiteMapping() {
    try {
      List<SubjectPrerequisiteMapResponse> responses = courseManagementClient.getPrerequisiteMapping();
      Map<UUID, Set<UUID>> map = new HashMap<>();
      for (SubjectPrerequisiteMapResponse r : responses) {
        if (r.getSubjectId() != null && r.getRelatedSubjectIds() != null) {
          map.put(r.getSubjectId(), new HashSet<>(r.getRelatedSubjectIds()));
        }
      }
      return map;
    } catch (Exception e) {
      log.warn("Failed to fetch prerequisite mapping, proceeding without it: {}", e.getMessage());
      return Map.of();
    }
  }

  private List<EnrichedEnrollment> buildEnrichedEnrollments(
      List<Enrollment> enrollments,
      Map<UUID, ClassSectionDatasetResponse> classMetaMap) {
    Map<UUID, ClassSectionDatasetResponse> validMeta = new HashMap<>();
    for (Enrollment e : enrollments) {
      ClassSectionDatasetResponse meta = classMetaMap.get(e.getClassId());
      if (meta != null && meta.getSubjectId() != null && meta.getSemesterId() != null && meta.getSemKey() != null) {
        validMeta.put(e.getClassId(), meta);
      }
    }

    List<Enrollment> sorted = enrollments.stream()
        .filter(e -> validMeta.containsKey(e.getClassId()))
        .sorted(Comparator.comparingInt(e -> validMeta.get(e.getClassId()).getSemKey()))
        .toList();

    Map<String, Integer> attemptCounter = new HashMap<>();
    List<EnrichedEnrollment> result = new ArrayList<>();
    for (Enrollment e : sorted) {
      ClassSectionDatasetResponse meta = validMeta.get(e.getClassId());
      double raw = e.getFinalGrade();
      double grade4 = convertTo4Point(raw);

      String attemptKey = e.getStudentId() + "|" + meta.getSubjectId();
      int attemptIndex = attemptCounter.getOrDefault(attemptKey, 0);
      attemptCounter.put(attemptKey, attemptIndex + 1);

      result.add(
          new EnrichedEnrollment(
              e.getStudentId(), e.getClassId(), meta.getSubjectId(), meta.getSemesterId(), meta.getSemKey(),
              meta.getCredits() != null ? meta.getCredits() : 0, raw, grade4, attemptIndex,
              meta.getCurriculumSectionId()));
    }
    return result;
  }

  private Map<String, Integer> computeSemCreditsMap(List<EnrichedEnrollment> enriched) {
    Map<String, Integer> map = new HashMap<>();
    for (EnrichedEnrollment e : enriched) {
      String key = compositeKey(e.studentId(), e.semesterId());
      map.merge(key, e.credits(), Integer::sum);
    }
    return map;
  }

  private StudentHistory computeStudentHistory(int currentSemKey, List<EnrichedEnrollment> studentRows) {
    List<EnrichedEnrollment> prior = studentRows.stream().filter(r -> r.semKey() < currentSemKey).toList();

    if (prior.isEmpty()) return StudentHistory.empty();

    Set<Integer> priorSemKeys = prior.stream().map(EnrichedEnrollment::semKey).collect(Collectors.toSet());
    int numSemestersPrior = priorSemKeys.size();

    // Cumulative credit-weighted avg (= current_gpa in Python)
    double sumWeightedGrade = 0, sumCredits = 0;
    for (EnrichedEnrollment r : prior) {
      sumWeightedGrade += r.courseGrade4pt() * r.credits();
      sumCredits += r.credits();
    }
    Double cumulativeAvg = sumCredits > 0 ? sumWeightedGrade / sumCredits : null;

    // Previous semester avg (latest semKey)
    int prevSemKey = priorSemKeys.stream().mapToInt(x -> x).max().orElse(0);
    List<EnrichedEnrollment> prevSemRows = prior.stream().filter(r -> r.semKey() == prevSemKey).toList();
    double prevSumWG = 0, prevSumC = 0;
    for (EnrichedEnrollment r : prevSemRows) {
      prevSumWG += r.courseGrade4pt() * r.credits();
      prevSumC += r.credits();
    }
    Double prevSemAvg = prevSumC > 0 ? prevSumWG / prevSumC : null;

    return new StudentHistory(numSemestersPrior, cumulativeAvg, prevSemAvg);
  }

  private Map<String, SubjectSemesterMetrics> batchLoadSubjectSemesterMetrics(List<EnrichedEnrollment> enriched) {
    Set<UUID> subjectIds = enriched.stream().map(EnrichedEnrollment::subjectId).collect(Collectors.toSet());
    Set<UUID> semesterIds = enriched.stream().map(EnrichedEnrollment::semesterId).collect(Collectors.toSet());
    return subjectSemesterMetricsService.batchLoadMetrics(new ArrayList<>(subjectIds), new ArrayList<>(semesterIds));
  }

  private CourseBaseline computeCourseBaseline(
      UUID subjectId, UUID semesterId,
      Map<String, SubjectSemesterMetrics> metricsMap) {
    // Look up in pre-loaded batch map (O(1) instead of DB query)
    String key = subjectId + "|" + semesterId;
    SubjectSemesterMetrics metrics = metricsMap.get(key);

    if (metrics == null) {
      log.warn("Subject metric not found for subjectId={} semesterId={}", subjectId, semesterId);
      return new CourseBaseline(0, 0.0, true, true);
    }

    boolean isFallback = metrics.getIsFallback();
    if (isFallback) {
      log.warn(
          "Course baseline for subjectId={} semesterId={} is using fallback data (fallbackLevel={}). " + "This " +
              "record" + " will be filtered out from dataset.",
          subjectId, semesterId, metrics.getFallbackLevel());
    }

    // Use pre-computed smoothed median (4-point scale) directly from batch-loaded metrics
    int sampleCount = metrics.getSampleCount();
    double smoothedMedian4pt = metrics.getSmoothedMedian4pt();

    return new CourseBaseline(sampleCount, smoothedMedian4pt, false, isFallback);
  }

  /**
   * Compute relative course features using UNION of:
   * <ol>
   *   <li>Same curriculumSectionId (subjects in the same curriculum section)</li>
   *   <li>Prerequisite / Recommended courses (from course_prerequisites table)</li>
   * </ol>
   * Only uses courses the student took in PRIOR semesters (no data leakage).
   * Matches Python: add_relative_course_features()
   */
  private RelativeCourseResult computeRelativeAvgCourseGrade(
      EnrichedEnrollment row,
      Map<UUID, List<EnrichedEnrollment>> byStudent, Map<UUID, Set<UUID>> prereqMap) {
    List<EnrichedEnrollment> studentPrior = byStudent.getOrDefault(row.studentId(), List.of())
        .stream()
        .filter(r -> r.semKey() < row.semKey())
        .toList();

    if (studentPrior.isEmpty()) {
      return new RelativeCourseResult(false, null);
    }

    // Build UNION mask: same curriculumSectionId OR is prerequisite/recommended of current course
    Set<UUID> relatedSubjectIds = prereqMap.getOrDefault(row.subjectId(), Set.of());
    UUID currentCurriculumSectionId = row.curriculumSectionId();

    List<EnrichedEnrollment> relatedRows = studentPrior.stream().filter(r -> {
      // 1) Same curriculum section (subjects in same section are related)
      if (currentCurriculumSectionId != null && currentCurriculumSectionId.equals(r.curriculumSectionId())) {
        return true;
      }
      // 2) Is prerequisite/recommended of current course
      return relatedSubjectIds.contains(r.subjectId());
    }).toList();

    if (relatedRows.isEmpty()) {
      return new RelativeCourseResult(false, null);
    }

    // Credit-weighted avg grade
    double sumWG = 0, sumC = 0;
    for (EnrichedEnrollment r : relatedRows) {
      sumWG += r.courseGrade4pt() * r.credits();
      sumC += r.credits();
    }

    if (sumC == 0) return new RelativeCourseResult(false, null);
    double relativeAvg = sumWG / sumC;
    return new RelativeCourseResult(true, relativeAvg);
  }


  // add_course_history_baseline, impute_course_level, finalize_other_features)


  /**
   * Step 1: Student-level imputation (reduced).
   * Missing GPA fields default to 0.
   */
  private void imputeStudentLevel(List<RawFeatureRow> rows) {
    // Group by student to ensure no cross-student data leakage
    Map<UUID, List<RawFeatureRow>> byStudent = rows.stream().collect(Collectors.groupingBy(r -> r.row.studentId()));

    for (List<RawFeatureRow> studentRows : byStudent.values()) {
      // Sort each student's rows by semKey for temporal ordering
      studentRows.sort(Comparator.comparingInt(r -> r.row.semKey()));

      for (RawFeatureRow raw : studentRows) {
        boolean needsImpute = raw.history.numSemestersPrior() <= 0 || raw.history.cumulativeGradeAvg() == null;

        if (needsImpute) {
          raw.imputedCumulativeGradeAvg = 0.0;
          raw.imputedPreviousSemGradeAvg = 0.0;
        } else {
          raw.imputedCumulativeGradeAvg = orDefault(raw.history.cumulativeGradeAvg());
          raw.imputedPreviousSemGradeAvg = orDefault(raw.history.previousSemGradeAvg());
        }
      }
    }
  }

  /**
   * Step 2: Finalize other features (reduced).
   * relative_avg_course_grade defaults to previous semester GPA or 0 when missing.
   */
  private void imputeFinalize(List<RawFeatureRow> rows) {
    for (RawFeatureRow raw : rows) {
      if (!raw.relative.hasRelative()) {
        raw.imputedRelativeAvg = raw.imputedPreviousSemGradeAvg != null ? raw.imputedPreviousSemGradeAvg : 0.0;
      } else {
        raw.imputedRelativeAvg = orDefault(raw.relative.relativeAvg());
      }

      raw.imputedCumulativeGradeAvg = orDefault(raw.imputedCumulativeGradeAvg);
      raw.imputedPreviousSemGradeAvg = orDefault(raw.imputedPreviousSemGradeAvg);
    }
  }

  private GradePredictionDataset buildEntity(RawFeatureRow raw, UUID versionId) {
    EnrichedEnrollment row = raw.row;

    return GradePredictionDataset.builder()
        .studentId(row.studentId())
        .semesterId(row.semesterId())
        .subjectId(row.subjectId())
        .versionId(versionId)
        .courseGrade(row.courseGrade4pt())
        .semCredits(raw.semCredits)
        .semCreditsSquared(raw.semCredits * raw.semCredits)
        .retakeNo(row.attemptIndex())
        .numSemestersPrior(raw.history.numSemestersPrior())
        .cumulativeGradeAvg(raw.imputedCumulativeGradeAvg)
        .previousSemGradeAvg(raw.imputedPreviousSemGradeAvg)
        .subjectHistMedianSmooth(raw.baseline.histMedianSmooth())
        .relativeAvgCourseGrade(raw.imputedRelativeAvg)
        .build();
  }

  /**
   * Checks if a row has ALL features computed from real data (no imputation needed).
   * Records with any imputed features are filtered out of the dataset.
   */
  private boolean hasCompleteData(RawFeatureRow raw) {
    // Student history must have real data (student has prior semesters)
    boolean hasStudentHistory =
        raw.history.numSemestersPrior() > 0 && raw.history.cumulativeGradeAvg() != null && raw.history.previousSemGradeAvg() != null;

    // Course baseline must have real historical data (not fallback)
    boolean hasCourseHistory = !raw.baseline.histMissing() && !raw.baseline.isFallback();

    return hasStudentHistory && hasCourseHistory;
  }

  private void upsertBatch(List<GradePredictionDataset> entities, UUID versionId) {
    for (int i = 0; i < entities.size(); i += BATCH_SIZE) {
      int end = Math.min(i + BATCH_SIZE, entities.size());
      List<GradePredictionDataset> batch = entities.subList(i, end);

      // Extract fields into arrays for PostgreSQL unnest
      String[] studentIds = batch.stream().map(e -> e.getStudentId().toString()).toArray(String[]::new);
      String[] semesterIds = batch.stream().map(e -> e.getSemesterId().toString()).toArray(String[]::new);
      String[] subjectIds = batch.stream().map(e -> e.getSubjectId().toString()).toArray(String[]::new);

      Double[] courseGrades = batch.stream().map(GradePredictionDataset::getCourseGrade).toArray(Double[]::new);
      Integer[] semCredits = batch.stream().map(GradePredictionDataset::getSemCredits).toArray(Integer[]::new);
      Integer[] semCreditsSq = batch.stream().map(GradePredictionDataset::getSemCreditsSquared).toArray(Integer[]::new);
      Integer[] retakeNos = batch.stream().map(GradePredictionDataset::getRetakeNo).toArray(Integer[]::new);
      Integer[] numSems = batch.stream().map(GradePredictionDataset::getNumSemestersPrior).toArray(Integer[]::new);
      Double[] cumGrades = batch.stream().map(GradePredictionDataset::getCumulativeGradeAvg).toArray(Double[]::new);
      Double[] prevSemGrades = batch.stream()
          .map(GradePredictionDataset::getPreviousSemGradeAvg)
          .toArray(Double[]::new);
      Double[] histMedians = batch.stream()
          .map(GradePredictionDataset::getSubjectHistMedianSmooth)
          .toArray(Double[]::new);
      Double[] relAvgs = batch.stream().map(GradePredictionDataset::getRelativeAvgCourseGrade).toArray(Double[]::new);

      // TRUE batch upsert: single round trip for entire batch using PostgreSQL unnest
      datasetRepository.batchUpsert(
          versionId, studentIds, semesterIds, subjectIds, courseGrades, semCredits, semCreditsSq, retakeNos, numSems,
          cumGrades, prevSemGrades, histMedians, relAvgs);

      log.debug("Executed true batch upsert for {}/{} records", end, entities.size());
    }
  }

  private String compositeKey(UUID a, UUID b) {
    return a + "|" + b;
  }

  private static double orDefault(Double value) {
    return value != null ? value : 0.0;
  }

  private record EnrichedEnrollment(UUID studentId, UUID classId, UUID subjectId, UUID semesterId, int semKey,
                                    int credits, double finalGrade10pt, double courseGrade4pt, int attemptIndex,
                                    UUID curriculumSectionId) {
  }

  private record StudentHistory(int numSemestersPrior, Double cumulativeGradeAvg, Double previousSemGradeAvg) {
    static StudentHistory empty() {
      return new StudentHistory(0, null, null);
    }
  }

  private record CourseBaseline(int histCount, double histMedianSmooth, boolean histMissing, boolean isFallback) {
  }

  private record RelativeCourseResult(boolean hasRelative, Double relativeAvg) {
  }

  /**
   * Mutable container holding raw features + imputed values for one row.
   * Fields are filled in phases: Phase 7 (raw), then Phase 8 (imputation steps 1-4).
   */
  private static class RawFeatureRow {
    final EnrichedEnrollment row;
    final StudentHistory history;
    final CourseBaseline baseline;
    final RelativeCourseResult relative;
    final int semCredits;

    // Imputed student-level (Step 1)
    Double imputedCumulativeGradeAvg;
    Double imputedPreviousSemGradeAvg;

    // Imputed relative (Step 4)
    double imputedRelativeAvg;

    RawFeatureRow(
        EnrichedEnrollment row, StudentHistory history, CourseBaseline baseline,
        RelativeCourseResult relative, int semCredits) {
      this.row = row;
      this.history = history;
      this.baseline = baseline;
      this.relative = relative;
      this.semCredits = semCredits;
    }
  }
}
