INSERT INTO
    learning.grade_prediction_dataset_version (
    id,
    version_number,
    description,
    total_rows,
    status,
    created_at,
    updated_at,
    completed_at
)
VALUES
    (
        '763364fd-4bca-4780-aa4e-534bcc19723e'::uuid,
        1,
        'Auto-generated by ETL',
        18669,
        'COMPLETED',
        '2026-03-19 15:22:06.488017+07',
        '2026-03-19 15:22:33.307399+07',
        '2026-03-19 15:22:07.650309+07'
    );


INSERT INTO
    learning.training_job (
    id,
    job_id,
    dataset_version_id,
    model_name,
    s3_dataset_url,
    s3_model_url,
    status,
    training_time_seconds,
    error_message,
    created_at,
    updated_at,
    submitted_at,
    completed_at,
    description
)
VALUES
    (
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'TRAIN_20260319_153010_e5ec2c15',
        '763364fd-4bca-4780-aa4e-534bcc19723e'::uuid,
        'linear_grade_predictor_20260319_153010',
        's3://lms-wecancode/linear-grade-predictor-model/training-dataset/dataset_v1_2026-03-19T08-30-10-827169800Z.csv',
        's3://lms-wecancode/linear-grade-predictor-model/models/linear_grade_predictor_20260319_153010_2026-03-19T08-30-12.490934500Z.onnx',
        'COMPLETED',
        1.6858153343200684,
        NULL,
        '2026-03-19 15:30:12.852487+07',
        '2026-03-19 15:30:14.907165+07',
        '2026-03-19 15:30:12.776942+07',
        '2026-03-19 15:30:14.87954+07',
        NULL
    );

INSERT INTO
    learning.training_metrics (
    id,
    training_job_id,
    metric_type,
    dataset_split,
    scale_type,
    mae,
    rmse,
    r2,
    mu_error,
    sigma_error,
    sample_count,
    created_at,
    updated_at
)
VALUES
    (
        '7fd8daa6-62ce-4a78-ad1a-2e627d252aea'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'baseline',
        'train',
        'FOUR_POINT',
        0.9541731589796529,
        1.4036117636011882,
        -1.455021183326953,
        NULL,
        NULL,
        NULL,
        '2026-03-19 15:30:14.886032+07',
        '2026-03-19 15:30:14.886032+07'
    ),
    (
        'e864e791-48a9-4be9-adfd-9e740c4ef76c'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'model',
        'train',
        'FOUR_POINT',
        0.6872832082337034,
        0.8740336880980237,
        0.0480424354528568,
        NULL,
        NULL,
        NULL,
        '2026-03-19 15:30:14.889935+07',
        '2026-03-19 15:30:14.889935+07'
    ),
    (
        'dbacb8ba-a3cc-4261-a09a-183d672e6cc4'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'model',
        'train',
        'FOUR_POINT',
        NULL,
        NULL,
        NULL,
        -0.0000000000000001,
        0.874062997924765,
        14911,
        '2026-03-19 15:30:14.892664+07',
        '2026-03-19 15:30:14.892664+07'
    ),
    (
        '1e24995c-6cec-4851-be5f-5b5d2873624b'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'baseline',
        'test',
        'FOUR_POINT',
        0.9259237548506464,
        1.3711480426041582,
        -1.5463225689132316,
        NULL,
        NULL,
        NULL,
        '2026-03-19 15:30:14.895124+07',
        '2026-03-19 15:30:14.895124+07'
    ),
    (
        'eaa023ab-1ed5-4544-885a-5ca75010867c'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'model',
        'test',
        'FOUR_POINT',
        0.6639844100146781,
        0.8418636304717134,
        0.040095076863473245,
        NULL,
        NULL,
        NULL,
        '2026-03-19 15:30:14.896855+07',
        '2026-03-19 15:30:14.896855+07'
    ),
    (
        '809b2c28-544f-4f0d-b3f5-1ac3da9684fe'::uuid,
        '6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,
        'model',
        'test',
        'FOUR_POINT',
        NULL,
        NULL,
        NULL,
        -0.013655449974779575,
        0.8418648912157334,
        3758,
        '2026-03-19 15:30:14.899112+07',
        '2026-03-19 15:30:14.899112+07'
    );

INSERT INTO learning.model_version (id,version_name,model_name,training_job_id,dataset_version_id,s3_model_path,status,is_active,training_time_seconds,test_mae,test_rmse,test_r2,train_mae,train_rmse,train_r2,sample_count,test_mu_error,test_sigma_error,train_mu_error,train_sigma_error,description,created_at,updated_at) VALUES
    ('d8fb10fa-e8c3-435b-9458-08610e572241'::uuid,'linear_grade_predictor_20260319_153010','linear_grade_predictor_20260319_153010','6b01dfa3-51cf-4479-9604-14c74e6c2c03'::uuid,'763364fd-4bca-4780-aa4e-534bcc19723e'::uuid,'s3://lms-wecancode/linear-grade-predictor-model/models/linear_grade_predictor_20260319_153010_2026-03-19T08-30-12.490934500Z.onnx','ACTIVE',true,1.6858153343200684,0.6639844100146781,0.8418636304717134,0.040095076863473245,0.6872832082337034,0.8740336880980237,0.0480424354528568,3758,-0.013655449974779575,0.8418648912157334,-0.0000000000000001,0.874062997924765,NULL,'2026-03-19 15:30:14.903708+07','2026-03-19 15:32:12.559838+07');
