server:
  port: 8087

prefix-api: /api/personalization/v1

spring:
  application:
    name: personalization-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lms_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:lms_user}
    password: ${DB_PASSWORD:lms_password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: personalization
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: personalization
    default-schema: personalization
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history
    out-of-order: false
    validate-on-migrate: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      circuitbreaker:
        enabled: true

gemini:
  api-key: ${GEMINI_API_KEY:key-here}
  embedding-model-name: ${GEMINI_EMBEDDING_MODEL:models/gemini-embedding-001}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

