package com.hcmut.lms.coursemanagement.domain.entity.classSection;

public enum CourseLevel {
    BEGINNER,
    INTERMEDIATE,
    ADVANCED,
    GENERAL_EDUCATION,
    MAJOR_FOUNDATION,
    MAJOR_SPECIALIZATION,
    GRADUATION_REQUIREMENT,
    GENERAL_POLITICS_ECONOMICS_SOCIETY,
    GENERAL_FOREIGN_LANGUAGE,
    PHYSICAL_EDUCATION
}
